### ISSUE TITLE
Vision / Goal of the project

### ISSUE THREAD

**Issue by cookiengineer** [jdsutton/OnlineU#33]
Hey guys,

I was just checking out this project and so far I really like the idea and I want to contribute.

However, it is a bit unclear to me as a newcomer what the vision of the project is atm. is it being an alternative in terms for being a software third party users will modify in order to build their own khanacademy? Or is the focus on being an own, libre developed platform for end users directly?

The things in mind I have so far are:

- I would suggest to rename the project, because it's impossible to find via google and/or even in my own Browser history from reddit. I was crawling my history but `Online U` is impossible to remember for newcomers or foreigners to the project. (just a suggestion, because others might have the same problem).

I don't know of something catchy (would be another discussion), but something like "LibreUniversity" or so - we might wanna google some stuff first to decide what's not used!?

ninja edit: Maybe it makes sense to host stuff on github (see below), so something like unihub or coursehub would be awesome as a name (that's only my opinion) and easy to remember. Since last year there's also a `university TLD`, so something like `github.university` or `libre.university` would also be possible. The TLD has no requirements like the shitty `edu` registration process.

- Do you want to change the design or need a designer? I would love to help you guys shimming up everything. My strengths are mostly C++ and JS (ES6 and ES7 on OpenGL and libSDL) and HTML/CSS. I don't feel good enough in python to not mess up your python codebase. However, I would love to do all things native clients for Android, Linux and HTML5 website / clients.

- I had something similar to the project always in mind. What I would love is downloadable content that is available offline afterwards. Similar to some API docs crawling tools. So people can download the slides / materials and backup them properly to import or view them later. I _really_ would love to build up such a native client!

- Do you need hosting space? GitHub Pages (github.io) is free, so I would love to host the website there. Did that in the past and it worked like a charm (also works with your own domains / CNAMEs).

- Regarding API and data structure for users: It would be awesome to strictly have everything REST, so that we can easily build up native clients (for Tablets and Desktop computers) that feature offline caches for the course materials. For me it's a bit unclear atm where the actual data comes from and where the relevant code for it is.

- Better organization with a github orga. If you guys want to build up a native client and stuff (which I again, would love to build), I would recommend creating a github orga for the project when the name was discussed with all contributors. That would ease up the splitting-the-logic-from-data part.

Other random things I have in mind:

We could try building up a bot that uses github as storage (like repos in an orga for course materials). Only the database / CORS aspect is bothering me, but I think that can be easily fixed - worst case scenario would be using letsencrypt and then we're fine. Advantage of hosting all (scraped) course material in github repos would be the fork / update aspect of outdated material - so experienced users can fix the material or extend it with cool further links, projects, code demos etc.

Also, I would heavily recommend doing as much as possible in markdown, because it's much easier for non-techie end users.

Cheers, ~Chris

**Comment by jdsutton** [comment]
The aim of the project is to be a comprehensive, 100% free, online college. The course content will be created by qualified volunteer content curators, and possibly paid content curators if donations start coming in.

You're right about the name, "OnlineU" was meant to be a placeholder until I could come up with something better.

Yes, we do need a frontend designer. The visual appeal of the site and usability of the interface can always be improved. One quick improvement you could do is to make the user progress in a course shown as a progress bar rather than a numerical %.

I think with your background you could quickly pick up enough Python to help with the server-side things as well. If you look through `project.py` you will see some very common programming patterns you can emulate.

As for downloading content, I think that's a great idea. I see lots of users on Khan Academy asking about this, since they have unreliable connections. If you created a simple in-browser tool to download YouTube videos for later, I think that would be very useful.

We will be looking for permanent site hosting soon, as the site is almost ready to begin serving content. The server is python-based, so if we go with a service it will have to allow us to run that. We may also just purchase our own server.

There is some seed data in `database_setup.py`, and the site allows admins to directly create new content through it (you will see the admin interface if you make yourself an admin).

Having a REST API is a goal for the future. There is some example code for that commented out in `project.py`.

**Comment by jdsutton** [comment]
I think it might be a good idea to have some of the content stored on GitHub... I've been thinking about the best ways to allow curators to edit/store exams and GitHub might be a nice solution. The only problem I can think of is it might be not quite as easy to fetch the data, and GitHub might not be too happy about us putting an extra load on their servers.

Another big thing to consider is that we will need programming environments for Java, Python, and JavaScript.

**Comment by jdsutton** [comment]
@cookiengineer let me know if you have any other questions. I'll close this for now, but we can discuss more in the gitter chat.
